### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by leonoverweel** [gillyb/reimg#2]
I'm thinking about using this for a little project, but I don't see a license for the code. Is it MIT licensed (or something else), and can you add a file with the license? Thanks.

**Comment by gillyb** [comment]
I added the MIT license, in the file LICENSE.md, and also stated so in the readme file.
If this doesn't suit your needs please let me know, because the idea is to basically let anyone do anything with this... :)

I'll be happy if you let me know which project you're using this for ?
(But even if you don't or can't i'll understand)
